global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus'  # This is the default path provided by the Jenkins Prometheus plugin.
    static_configs:
      - targets: ['172.17.0.1:8080']
